# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fy_gapmCDM_IS <- function(Y, A, C, mu, R, Z, pM, pR, control) {
    .Call(`_pmCDM_fy_gapmCDM_IS`, Y, A, C, mu, R, Z, pM, pR, control)
}

fy_aCDM_IS <- function(Y, G, Qmatrix, Apat, mu, R, Z, pM, pR, control) {
    .Call(`_pmCDM_fy_aCDM_IS`, Y, G, Qmatrix, Apat, mu, R, Z, pM, pR, control)
}

gapmCDM_sim_rcpp <- function(n, q, p, A, C, mu, R, control) {
    .Call(`_pmCDM_gapmCDM_sim_rcpp`, n, q, p, A, C, mu, R, control)
}

gapmCDM_fit_rcpp <- function(Y, A, C, D, mu, R, Z, control) {
    .Call(`_pmCDM_gapmCDM_fit_rcpp`, Y, A, C, D, mu, R, Z, control)
}

gapmCDM_cv_rcpp <- function(Ytrain, Ytest, A, C, mu, R, Z, control) {
    .Call(`_pmCDM_gapmCDM_cv_rcpp`, Ytrain, Ytest, A, C, mu, R, Z, control)
}

apmCDM_sim_rcpp <- function(n, G, Qmatrix, Apat, mu, R) {
    .Call(`_pmCDM_apmCDM_sim_rcpp`, n, G, Qmatrix, Apat, mu, R)
}

apmCDM_fit_rcpp <- function(Y, G, Qmatrix, Apat, mu, R, Z, control) {
    .Call(`_pmCDM_apmCDM_fit_rcpp`, Y, G, Qmatrix, Apat, mu, R, Z, control)
}

apmCDM_cv_rcpp <- function(Ytrain, Ytest, G, Qmatrix, Apat, mu, R, Z, control) {
    .Call(`_pmCDM_apmCDM_cv_rcpp`, Ytrain, Ytest, G, Qmatrix, Apat, mu, R, Z, control)
}

D2C <- function(D) {
    .Call(`_pmCDM_D2C`, D)
}

genpar <- function(p, q, probSparse, knots, degree, basis) {
    .Call(`_pmCDM_genpar`, p, q, probSparse, knots, degree, basis)
}

genpar_aCDM <- function(Qmatrix, maxG0) {
    .Call(`_pmCDM_genpar_aCDM`, Qmatrix, maxG0)
}

fy_gapmCDM <- function(Y, A, C, mu, R, control) {
    .Call(`_pmCDM_fy_gapmCDM`, Y, A, C, mu, R, control)
}

fy_aCDM <- function(Y, G, Qmatrix, Apat, mu, R, control) {
    .Call(`_pmCDM_fy_aCDM`, Y, G, Qmatrix, Apat, mu, R, control)
}

