# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gapmCDM_sim_rcpp <- function(n, q, p, A, C, mu, R, control) {
    .Call(`_pmCDM_gapmCDM_sim_rcpp`, n, q, p, A, C, mu, R, control)
}

gapmCDM_fit_rcpp <- function(Y, A, C, D, mu, R, Z, control) {
    .Call(`_pmCDM_gapmCDM_fit_rcpp`, Y, A, C, D, mu, R, Z, control)
}

gapmCDM_cv_rcpp <- function(Ytrain, Ytest, A, C, mu, R, Z, control) {
    .Call(`_pmCDM_gapmCDM_cv_rcpp`, Ytrain, Ytest, A, C, mu, R, Z, control)
}

D2C <- function(D) {
    .Call(`_pmCDM_D2C`, D)
}

genpar <- function(p, q, probSparse, knots, degree, basis) {
    .Call(`_pmCDM_genpar`, p, q, probSparse, knots, degree, basis)
}

fy <- function(Y, A, C, mu, R, control) {
    .Call(`_pmCDM_fy`, Y, A, C, mu, R, control)
}

